import { ExploreArray, RecommendedArray } from "data/data";

import Head from "next/head";
import React from "react";

/* import trojenaBg from "../public/images/trojena-bg.jpg";
 */
/* import profilePic from "../public/images/hotel-5.png"; */
/* import { ExploreArray } from "data/data"; */
let openidwindow = null;
const url =
  "https://idp.kobilshift-app01-eotsr.shift.kobil.com/auth/realms/flutter/protocol/openid-connect/auth?client_id=test-openid&redirect_uri=https://neom-hotel.web.app/code&scope=openid&response_type=code&response_mode=query&nonce=o3w1vsredlp&prompt=none";
function Code() {
  const [code, setCode] = React.useState(null);

  /*  React.useEffect(() => {
    setTimeout(() => {
      const result = document.getElementById("iframe").src;
      alert(result);
    }, 3000);
     
  }, []); */

  /*   React.useEffect(() => {
    if (!code) {
      setTimeout(() => {
        const a = window.location.assign(
          "https://idp.kobilshift-app01-eotsr.shift.kobil.com/auth/realms/flutter/protocol/openid-connect/auth?client_id=test-openid&redirect_uri=http://test:3000/code&scope=openid&response_type=code&response_mode=query&nonce=o3w1vsredlp"
        );
      }, 1);
    }
    return () => {};
  }, [code]); */

  return (
    <div>
      <Head>
        <title>Neom Hotels</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <iframe id="iframe" src={url} width={400} height={400}></iframe>
      Code : {code}
      {/* <button
        id="frame"
        onClick={() => {
          openidwindow = window.open(
            "https://idp.kobilshift-app01-eotsr.shift.kobil.com/auth/realms/flutter/protocol/openid-connect/auth?client_id=test-openid&redirect_uri=http://test:3000/code&scope=openid&response_type=code&response_mode=query&nonce=o3w1vsredlp&prompt=none",
            "_blank",
            "toolbar=0,location=0,menubar=0"
          );
          alert(openidwindow);
          console.log(openidwindow);
        }}
      >
        aa
      </button> */}
    </div>
  );
}

export default Code;
