import { ExploreArray, RecommendedArray, SearchRegionArray } from "data/data";

import Head from "next/head";
import React, { useEffect } from "react";
import HomeMenu from "@/components/HomeComponents/HomeMenu";
import Explore from "@/components/HomeComponents/Explore";
/* import Favorites from "@/components/HomeComponents/Favorites";
 */ import HeaderTitle from "@/components/HeaderTitle";
import Stays from "@/components/HomeComponents/Stays";
import SearchBar from "@/components/SearchBar";
import Back from "@/components/icons/Back";
import SearchContent from "@/components/HomeComponents/SearchContent";
import { getHomeActiveTab, saveRegion } from "data/api";
import Router, { useRouter } from "next/router";
import dynamic from "next/dynamic";
import { Navbar, Page } from "framework7-react";
import { useRouterPush } from "@/utils/hooks";
import F7Navbar from "@/components/F7Navbar";
const Favorites = dynamic(
  () => import("@/components/HomeComponents/Favorites"),
  {}
);

export async function getStaticProps() {
  return {
    props: {},
  };
}
function Home({
  exploreArray = ExploreArray,
  recommendedArray = RecommendedArray,
  searchData = SearchRegionArray,
  f7router,
}) {
  const [activeMenu, setActiveMenu] = React.useState("Explore");
  const [focusedSearch, setFocusedSearch] = React.useState(false);
  const [searchTerm, setSearchTerm] = React.useState("");
  const push = useRouterPush();
  const [user, setUser] = React.useState(null);
  const router = useRouter();

  React.useEffect(() => {
    try {
      if (activeMenu) {
        window.document?.getElementById("exploreContainer")?.scroll(0, 105);
      }
    } catch (error) {}
  }, [activeMenu]);

  React.useEffect(() => {
    const active = getHomeActiveTab();
    /* localStorage.removeItem("userinfo"); */

    if (active) {
      setActiveMenu(active);
    }
    /* console.log("active", active); */
  }, []);

  const generateUrl = (redirectUri) => {
    const url =
      process.env.openidHost +
      "protocol/openid-connect/auth?client_id=" +
      process.env.openIdClient +
      "&redirect_uri=" +
      redirectUri +
      "&scope=openid&response_type=code&response_mode=query&nonce=o3w1vsredlp";
    /* &prompt=none */
    return url;
  };

  React.useEffect(() => {
    if (!router.isReady) {
      return;
    }
    const _login = async () => {
      const address = window.location.protocol + "//" + window.location.host;

      if (user) {
        return;
      }
      const _user = await checkLogin();

      if (_user) {
        setUser(_user);
        return;
      }
      const urlParams = new URLSearchParams(window.location.href);
      const myParam = urlParams.get("code");
      if (myParam) {
        login(myParam, address, generateUrl(address));
      } else {
        /* alert("redirect"); */
        window.location.assign(generateUrl(address));
      }
    };
    _login();
  }, [router]);

  const checkLogin = async () => {
    try {
      const user = localStorage.getItem("userinfo");

      if (user) {
        let userObj = JSON.parse(user);
        if (userObj.expire > new Date().getTime()) {
          return userObj;
        }
      }
      return null;
    } catch (error) {
      return null;
    }
  };
  const login = async (code, redirectUri, authAddress) => {
    var myHeaders = new Headers();
    myHeaders.append("Content-Type", "application/json");

    try {
      const response = await fetch(process.env.openIdRequest, {
        method: "POST",
        headers: myHeaders,
        body: JSON.stringify({
          code: code,
          redirect_uri: redirectUri,
        }),
      });

      if (!response.ok) {
        /* alert("response not ok"); */
        throw await response.json();
      }

      const apiResultJson = await response.json();
      /* alert(JSON.stringify(result)); */
      console.log(apiResultJson);
      const userObj = apiResultJson.result;

      userObj.expire = new Date().getTime() + 30 * 60 * 60 * 1000 * 30;

      localStorage.setItem("userinfo", JSON.stringify(userObj));

      setUser(userObj);
      console.log(userObj);
    } catch (error) {
      console.log("err", error);
      /* alert("error login, redirect call"); */
      console.log("error", JSON.stringify(error));
      window.location.assign(authAddress);
    }
  };
  React.useEffect(() => {
    // Prefetch the dashboard page
    setTimeout(() => {
      Router.prefetch("/date-selection");
      Router.prefetch("/hotel-detail");
    }, 500);
  }, []);

  /*  React.useEffect(() => {
    // Prefetch the dashboard page
    alert("active" + activeMenu);
  }, [activeMenu]);
 */
  return (
    <Page>
      <div className={"container"}>
        <Head>
          <title>Neom Hotels</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        {(activeMenu === "Explore" || focusedSearch) && (
          <F7Navbar className="header">
            <HeaderTitle>
              <div style={{ marginRight: 6 }}>HI</div>
              {user ? (
                user.given_name ? (
                  user.given_name + ","
                ) : (
                  " Guest" + ","
                )
              ) : (
                <div
                  style={{
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                  }}
                >
                  <div
                    className="shine"
                    style={{ width: 100, height: 16, marginLeft: 4 }}
                  ></div>
                </div>
              )}
            </HeaderTitle>
          </F7Navbar>
        )}
        {/* <BottomSheet></BottomSheet> */}
        {/* <motion.div
          key={activeMenu}
          initial={{ opacity: 0.5, x: -50 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ ease: "easeOut", duration: 0.5 }}
        > */}
        {activeMenu === "Explore" && (
          <>
            <div className="exploreContainer" id="exploreContainer">
              <div className="searchContainer">
                <div className="search">
                  {focusedSearch && (
                    <Back
                      style={{ alignSelf: "center" }}
                      onClick={() => {
                        setFocusedSearch(false);
                        setSearchTerm("");
                      }}
                    ></Back>
                  )}
                  <SearchBar
                    value={searchTerm}
                    onFocus={() => {
                      setFocusedSearch(true);
                    }}
                    onChange={(e) => {
                      setSearchTerm(e.target.value);
                    }}
                  ></SearchBar>
                </div>
                {focusedSearch ? (
                  <SearchContent
                    searchTerm={searchTerm}
                    searchData={searchData}
                    onClick={(value) => {
                      saveRegion(value);
                      push("/date-selection", f7router);
                      /*  Router.push({
                        pathname: "/date-selection",
                      }); */
                    }}
                  ></SearchContent>
                ) : (
                  <Explore
                    exploreArray={exploreArray}
                    recommendedArray={recommendedArray}
                    user={user}
                    f7router={f7router}
                  ></Explore>
                )}
              </div>
              {!focusedSearch && <div className="any"></div>}
            </div>
          </>
        )}
        {activeMenu === "Favorites" && (
          <Favorites recommendedArray={recommendedArray} f7router={f7router} />
        )}
        {activeMenu === "Stays" && <Stays f7router={f7router} />}{" "}
        {/* </motion.div> */}
        {!focusedSearch && (
          <>
            <HomeMenu
              activeMenu={activeMenu}
              setActiveMenu={setActiveMenu}
            ></HomeMenu>
          </>
        )}
        <style jsx>{`
          .search {
            padding-right: 24px;
            width: 100%;
            margin-top: 41px;
            margin-bottom: 16px;
            display: flex;
            flex: 1;
          }

          .exploreContainer {
            position: relative;
            overflow: scroll;
            height: ${focusedSearch ? "unset" : "95vh"};

            /* transform: translateY(-200px); */
          }
          .searchContainer {
            /* background-color: yellow; */
          }
          .header {
            height: 58px;
            display: flex;
            align-items: center;
          }
          .any {
            height: 120px;
          }
          .container {
            padding-left: 24px;
            height: 100vh;
            overflow: hidden;
            flex: 1;
            display: flex;
            flex-direction: column;
          }
        `}</style>
      </div>{" "}
    </Page>
  );
}

export default Home;
