import { ExploreArray, RecommendedArray } from "data/data";

import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import HomeMenu from "@/components/HomeMenu";
/* import Explore from "@/components/home/Explore"; */
/* import Favorites from "@/components/home/Favorites"; */
import dynamic from "next/dynamic";
const Favorites = dynamic(() => import("@/components/home/Favorites"), {});
const Explore = dynamic(() => import("@/components/home/Explore"), {});

/* import trojenaLogo from "../public/images/logos/trojena.jpg"; */
/* import trojenaBg from "../public/images/trojena-bg.jpg";
 */
/* import profilePic from "../public/images/hotel-5.png"; */
/* import { ExploreArray } from "data/data"; */

export async function getStaticProps() {
  return {
    props: {
      exploreArray: ExploreArray,
      recommendedArray: RecommendedArray,
    },
  };
}
function Home({ exploreArray, recommendedArray }) {
  const [activeMenu, setActiveMenu] = React.useState("Explore");

  return (
    <div className={styles.container}>
      <Head>
        <title>Neom Hotels</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {activeMenu === "Explore" && (
        <Explore
          exploreArray={exploreArray}
          recommendedArray={recommendedArray}
        ></Explore>
      )}
      {activeMenu === "Favorites" && (
        <Favorites recommendedArray={recommendedArray} />
      )}
      <div style={{ height: 80 }}></div>
      <HomeMenu
        activeMenu={activeMenu}
        setActiveMenu={setActiveMenu}
      ></HomeMenu>
    </div>
  );
}

export default Home;
