import ExploreCard from "@/components/ExploreCard";
import HeaderTitle from "@/components/HeaderTitle";
import OptimizedImage from "@/components/OptimizedImage";
import RecommendedCard from "@/components/RecommendedCard";
import { ExploreArray, RecommendedArray } from "data/data";

import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import HomeMenu from "@/components/HomeMenu";
/* import trojenaLogo from "../public/images/logos/trojena.jpg"; */
/* import trojenaBg from "../public/images/trojena-bg.jpg";
 */
/* import profilePic from "../public/images/hotel-5.png"; */
/* import { ExploreArray } from "data/data"; */

export async function getStaticProps() {
  return {
    props: {
      exploreArray: ExploreArray,
      recommendedArray: RecommendedArray,
    },
  };
}
function Home({ exploreArray, recommendedArray }) {
  const [activeMenu, setActiveMenu] = React.useState("Explore");
  return (
    <div className={styles.container}>
      <Head>
        <title>Neom Hotels</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.header}>
        <HeaderTitle>HI EMILY,</HeaderTitle>
      </div>
      <div style={{ height: 24 }}></div>
      <div className={styles.title}>Explore by NEOM Region</div>
      <div className={styles.exploreContainer}>
        {exploreArray.map((item) => {
          return (
            <ExploreCard
              key={item.title}
              title={item.title}
              description={item.description}
              img={item.img}
              logo={item.logo}
            ></ExploreCard>
          );
        })}
      </div>
      <div style={{ height: 24 }}></div>
      <div className={styles.title}>Recommended For You</div>
      <div className={styles.recommendedContainer}>
        {recommendedArray.map((item) => {
          return (
            <RecommendedCard
              key={item.title}
              title={item.title}
              subTitle={item.subTitle}
              block={item.block}
              img={item.img}
              price={item.price}
              discountPrice={item.discountPrice}
            ></RecommendedCard>
          );
        })}
      </div>
      <HomeMenu
        activeMenu={activeMenu}
        setActiveMenu={setActiveMenu}
      ></HomeMenu>
    </div>
  );
}

export default Home;
